import json
import logging
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)


class TelegramResponseExtractor:
	"""
	Extracts the latest agent response directly from the IDE's overview.txt log file.
	This bypasses gRPC trajectory truncation issues.
	"""

	def __init__(self, brain_dir: Optional[Path] = None):
		self.brain_dir = brain_dir or (Path.home() / ".gemini" / "antigravity" / "brain")

	def get_latest_response(self, cascade_id: str) -> Optional[str]:
		overview_path = self.brain_dir / cascade_id / ".system_generated" / "logs" / "overview.txt"

		if not overview_path.exists():
			logger.warning(f"Overview log not found at {overview_path}. Fallback required.")
			return None

		try:
			with open(overview_path, "r", encoding="utf-8") as f:
				lines = f.readlines()

			for line in reversed(lines):
				if not line.strip():
					continue
				try:
					data = json.loads(line)
					# We are looking for the last PLANNER_RESPONSE generated by the MODEL
					if data.get("source") == "MODEL" and data.get("type") == "PLANNER_RESPONSE":
						content = data.get("content")
						if isinstance(content, str) and content:
							return content
				except json.JSONDecodeError:
					continue

		except Exception as e:
			logger.error(f"Failed to extract response from {overview_path}: {e}")

		return None
