import os
import subprocess


def main():
	project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
	cli_path = os.path.join(project_root, "src", "red_pill", "cli.py")
	docs_dir = os.path.join(project_root, "docs")
	os.makedirs(docs_dir, exist_ok=True)

	out_file = os.path.join(docs_dir, "CLI_REFERENCE.md")

	res = subprocess.run(["python3", cli_path, "--help"], capture_output=True, text=True)

	with open(out_file, "w") as f:
		f.write("# 🔴 BÜNKER COMMAND LINE INTERFACE\n\n")
		f.write("## Minimal Usage Examples\n")
		f.write("- **Start background daemon:** `red-pill run`\n")
		f.write("- **Run security audit on a codebase:** `red-pill audit /path/to/project`\n")
		f.write("- **Export encrypted soul-kit:** `red-pill soul export`\n\n")
		f.write("## Command Reference\n")
		f.write("```text\n")
		f.write(res.stdout)
		f.write("```\n\n")
		f.write("> Auto-generated by Agent Antigravity. Always trust the `--help` output.\n")

	print(f"Generated CLI Reference at {out_file}")


if __name__ == "__main__":
	main()
