FROM ubuntu:24.04

# Dependencias del sistema
RUN apt-get update && apt-get install -y \
    python3 python3-pip python3-venv sqlite3 \
    curl git tar sudo \
    && rm -rf /var/lib/apt/lists/*

# Simular el usuario del sistema operativo (para probar las rutas del $HOME)
RUN useradd -m -s /bin/bash aleth && echo "aleth ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
USER aleth
WORKDIR /home/aleth

# Entorno Python inmutable
RUN python3 -m venv /home/aleth/venv
ENV PATH="/home/aleth/venv/bin:$PATH"

# Comando por defecto (sobreescrito por compose)
CMD ["/bin/bash"]
